version: "3"

services:
  nginx:
    build: ./
    image : main-proxy:1.0.0
    container_name: main-proxy
    ports:
      - "80:80"
    networks:
      - frontend
    restart: always

networks:
  frontend:
